// Code generated by "stringer -type=ScaffoldTemplateKind -linecomment"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScaffoldTemplateLayout-0]
	_ = x[ScaffoldTemplateList-1]
	_ = x[ScaffoldTemplateDetail-2]
	_ = x[ScaffoldTemplateForm-3]
	_ = x[ScaffoldTemplateOpenAPI-4]
}

const _ScaffoldTemplateKind_name = "layoutlistdetailformopenapi"

var _ScaffoldTemplateKind_index = [...]uint8{0, 6, 10, 16, 20, 27}

func (i ScaffoldTemplateKind) String() string {
	if i < 0 || i >= ScaffoldTemplateKind(len(_ScaffoldTemplateKind_index)-1) {
		return "ScaffoldTemplateKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScaffoldTemplateKind_name[_ScaffoldTemplateKind_index[i]:_ScaffoldTemplateKind_index[i+1]]
}
